//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACBACustomer.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACBACustomer.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That type of document already exist.
        /// </summary>
        internal static string AddDocument_Error_Message {
            get {
                return ResourceManager.GetString("AddDocument_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string AddDocument_Error_Message_Title {
            get {
                return ResourceManager.GetString("AddDocument_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document added successfully.
        /// </summary>
        internal static string AddDocument_Succeddful_Message {
            get {
                return ResourceManager.GetString("AddDocument_Succeddful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successfull.
        /// </summary>
        internal static string AddDocument_Succeddful_Message_Title {
            get {
                return ResourceManager.GetString("AddDocument_Succeddful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_Button_Text {
            get {
                return ResourceManager.GetString("Delete_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer removing failed.
        /// </summary>
        internal static string Delete_Error_Message {
            get {
                return ResourceManager.GetString("Delete_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string Delete_Error_Message_Title {
            get {
                return ResourceManager.GetString("Delete_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details deleted successfully.
        /// </summary>
        internal static string Delete_Successful_Message {
            get {
                return ResourceManager.GetString("Delete_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfull.
        /// </summary>
        internal static string Delete_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Delete_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the following..
        /// </summary>
        internal static string Error_Document_Message_Header {
            get {
                return ResourceManager.GetString("Error_Document_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the following..
        /// </summary>
        internal static string Error_Message_Header {
            get {
                return ResourceManager.GetString("Error_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export_Button_Text {
            get {
                return ResourceManager.GetString("Export_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login_Button_Text {
            get {
                return ResourceManager.GetString("Login_Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Login_Password_Label_Text {
            get {
                return ResourceManager.GetString("Login_Password_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Login_Username_Label_Text {
            get {
                return ResourceManager.GetString("Login_Username_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username and password..
        /// </summary>
        internal static string Login_Validation_Message {
            get {
                return ResourceManager.GetString("Login_Validation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Message.
        /// </summary>
        internal static string Login_Validation_Message_Title {
            get {
                return ResourceManager.GetString("Login_Validation_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh_Button_Text {
            get {
                return ResourceManager.GetString("Refresh_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string Registration_Country_Required_Text {
            get {
                return ResourceManager.GetString("Registration_Country_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Registration_DateOfBirth_Label_Text {
            get {
                return ResourceManager.GetString("Registration_DateOfBirth_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        internal static string Registration_DateOfIssue_Label_Text {
            get {
                return ResourceManager.GetString("Registration_DateOfIssue_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string Registration_Document_Error_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Document_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number is required..
        /// </summary>
        internal static string Registration_DocumentNumber_Required_Text {
            get {
                return ResourceManager.GetString("Registration_DocumentNumber_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string Registration_Email_Required_Text {
            get {
                return ResourceManager.GetString("Registration_Email_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the Email.
        /// </summary>
        internal static string Registration_Email_Valid_Text {
            get {
                return ResourceManager.GetString("Registration_Email_Valid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string Registration_Error_Message {
            get {
                return ResourceManager.GetString("Registration_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error.
        /// </summary>
        internal static string Registration_Error_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string Registration_Firstname_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Firstname_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname is required..
        /// </summary>
        internal static string Registration_Firstname_Required_Text {
            get {
                return ResourceManager.GetString("Registration_Firstname_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Registration_Gender_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Gender_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required..
        /// </summary>
        internal static string Registration_Gender_Select_Text {
            get {
                return ResourceManager.GetString("Registration_Gender_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Authority is required..
        /// </summary>
        internal static string Registration_IssuingAuthority_Required_Text {
            get {
                return ResourceManager.GetString("Registration_IssuingAuthority_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string Registration_Lastname_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Lastname_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname is required..
        /// </summary>
        internal static string Registration_Lastname_Required_Text {
            get {
                return ResourceManager.GetString("Registration_Lastname_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string Registration_Save_Button_Text {
            get {
                return ResourceManager.GetString("Registration_Save_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer registered successfully!.
        /// </summary>
        internal static string Registration_Successful_Message {
            get {
                return ResourceManager.GetString("Registration_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        internal static string Registration_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeOfDocument .
        /// </summary>
        internal static string Registration_TypeOfDocument_Label_Text {
            get {
                return ResourceManager.GetString("Registration_TypeOfDocument_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeOfDocument is required.
        /// </summary>
        internal static string Registration_TypeOfDocument_Select_Text {
            get {
                return ResourceManager.GetString("Registration_TypeOfDocument_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document removing failed.
        /// </summary>
        internal static string RemoveDocument_Error_Message {
            get {
                return ResourceManager.GetString("RemoveDocument_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string RemoveDocument_Error_Message_Title {
            get {
                return ResourceManager.GetString("RemoveDocument_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document removed successfully.
        /// </summary>
        internal static string RemoveDocument_Successful_Message {
            get {
                return ResourceManager.GetString("RemoveDocument_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove - Document.
        /// </summary>
        internal static string RemoveDocument_Successful_Message_Title {
            get {
                return ResourceManager.GetString("RemoveDocument_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Button_Text {
            get {
                return ResourceManager.GetString("Search_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! System error. Please contact administrator..
        /// </summary>
        internal static string System_Error_Message {
            get {
                return ResourceManager.GetString("System_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string System_Error_Message_Title {
            get {
                return ResourceManager.GetString("System_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update_Button_Text {
            get {
                return ResourceManager.GetString("Update_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details updating failed.
        /// </summary>
        internal static string Update_Error_Message {
            get {
                return ResourceManager.GetString("Update_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error.
        /// </summary>
        internal static string Update_Error_Message_Title {
            get {
                return ResourceManager.GetString("Update_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details updated successfully.
        /// </summary>
        internal static string Update_Successful_Message {
            get {
                return ResourceManager.GetString("Update_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfull.
        /// </summary>
        internal static string Update_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Update_Successful_Message_Title", resourceCulture);
            }
        }
    }
}
